---
- file: path=/etc/prometheus state=directory

- template: src=prometheus.yml.j2 dest=/etc/prometheus/prometheus.yml
  register: conf

- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/prometheus.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/prometheus.yml up -d --force-recreate
  when: conf.changed or compose.changed

- name: Routing for prometheus
  command: >
    curl -XPUT -f -d '{"routes":[{"host":"prometheus.{{ env_domain }}"}]}' http://127.0.0.1:8500/v1/kv/services/routes/system/prometheus
  when: conf.changed or compose.changed
