---
- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/rabbitmq.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/rabbitmq.yml up -d --force-recreate
  when: compose.changed

- name: Routing for rabbitmq admin panel
  command: >
    curl -XPUT -f -d '{"routes":[{"host":"rabbit-web.{{ env_domain }}"}]}' http://127.0.0.1:8500/v1/kv/services/routes/system/rabbitmq
  when: compose.changed
