---
- file: path={{ webdav_path }}/upload state=directory

- name: Copy configs
  template: src="{{ item }}.j2" dest={{ webdav_path }}/{{ item }}
  with_items:
    - webdav.passwd
    - nginx.conf
  register: confs

- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/webdav.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/webdav.yml up -d --force-recreate
  when: compose.changed or confs.changed

- name: Http routing
  command: >
    curl -XPUT -f -d '{"routes":[{"host":"uploads.{{ env_domain }}"}]}' http://127.0.0.1:8500/v1/kv/services/routes/system/webdav
  when: compose.changed
