---
- file: path={{ webdav_path }}/upload state=directory

- name: Copy configs
  template: src="{{ item }}.j2" dest={{ webdav_path }}/{{ item }}
  with_items:
    - webdav.passwd
    - nginx.conf
  register: confs

- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/webdav.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/webdav.yml up -d --force-recreate
  when: compose.changed or confs.changed

- name: Save http routing
  uri:
    url: http://127.0.0.1:8500/v1/kv/services/routes/system/webdav
    method: PUT
    body_format: json
    body: '{ "routes": [ { "host": "uploads.{{ env_domain }}" } ] }'
  when: compose.changed
