---
- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/artifactory.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/artifactory.yml up -d --force-recreate
  when: compose.changed

- name: Http routing
  command: >
    curl -XPUT -f -d '{"routes":[{"host":"art.{{ inf_domain }}" {{ inf_domain_ssl_routes }} }]}' http://127.0.0.1:8500/v1/kv/services/routes/system/artifactory
  when: compose.changed
