---
- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/gitlab.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/gitlab.yml up -d --force-recreate
  when: compose.changed

- name: Http routing
  command: >
    curl -XPUT -f -d '{"routes":[{"host":"gitlab.{{ inf_domain }}"}]}' http://127.0.0.1:8500/v1/kv/services/routes/system/gitlab
  when: compose.changed
