---
- name: Copy docker-compose for localshop
  template: src=docker-compose.yml.j2 dest=/etc/compose/localshop.yml
  register: compose

- name: Run docker container with localshop
  command: docker-compose --file=/etc/compose/localshop.yml up -d --force-recreate
  when: compose.changed

- name: Routing for localshop
  command: >
    curl -XPUT -f -d '{"routes":[{"host":"localshop.{{ inf_domain }}" {{ inf_domain_ssl_routes }} }]}' http://127.0.0.1:8500/v1/kv/services/routes/system/localshop
  when: compose.changed
