---
- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/consul-server.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/consul-server.yml up -d --force-recreate
  when: compose.changed

- name: Wait while consul starting
  pause: seconds=20
  when: compose.changed

- name: Save http routing
  uri:
    url: http://127.0.0.1:8500/v1/kv/services/routes/system/consul-ui
    method: PUT
    body_format: json
    body: '{ "routes": [ { "host": "consul.{{ env_domain }}" } ] }'
  when: compose.changed
