---
- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/consul-server.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/consul-server.yml up -d --force-recreate
  when: compose.changed

- name: Wait while consul starting
  pause: seconds=20
  when: compose.changed

- name: Save http routing
  uri:
    url: http://127.0.0.1:8500/v1/kv/services/routes/system/consul-ui
    method: PUT
    body_format: json
    body: '{ "routes": [ { "host": "consul.{{ env_domain }}" } ] }'
  when: compose.changed

- cron:
    name: "Backup consul data"
    minute: 30
    hour: 1
    cron_file: "consul-backup"
    user: root
    job: >
      curl http://127.0.0.1:8500/v1/snapshot -o /var/data/consul/consul-snapshot.tgz
      && docker run --rm -v /var/data/consul:/data:ro -v /etc/{{ project_name }}/secrets/aws-backup-s3cfg:/root/.s3cfg
      samepagelabs/s3cmd put /data/consul-snapshot.tgz s3://{{ s3_backet_for_backups }}/consul/snapshot-`date +\%d`.tgz
  when: s3_backet_for_backups is defined and s3_backet_for_backups != ""
