---
- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/node-exporter.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/node-exporter.yml up -d --force-recreate
  when: compose.changed
