---
# A lightweight private npm proxy registry

- name: Copy docker-compose for verdaccio
  template: src=docker-compose.yml.j2 dest=/etc/compose/verdaccio.yml
  register: compose

- file: path=/var/data/verdaccio/storage mode=a+w state=directory

- name: Run docker container with verdaccio
  command: docker-compose --file=/etc/compose/verdaccio.yml up -d --force-recreate
  when: compose.changed

- name: Routing for verdaccio
  command: >
    curl -XPUT -f -d '{"routes":[
        {"host":"npm.{{ inf_domain }}" {{ inf_domain_ssl_routes }} },
        {"host":"npm.{{ inf_domain }}","location":"~ ^/-/.+" {{ inf_domain_ssl_routes }} }
      ]}' http://127.0.0.1:8500/v1/kv/services/routes/system/verdaccio
  when: compose.changed
