---
- name: Cleanup old serve versions
  shell: rm -f /usr/local/bin/serve-v*-linux-amd64
  args:
    creates: /usr/local/bin/serve-v{{ version }}-linux-amd64

- name: Download latest serve release
  command: curl -Lfvs "https://github.com/servehub/serve/releases/download/v{{ version }}/serve-v{{ version }}-linux-amd64" -o /usr/local/bin/serve-v{{ version }}-linux-amd64
  args:
    creates: /usr/local/bin/serve-v{{ version }}-linux-amd64
  register: newver

- copy: src=/usr/local/bin/serve-v{{ version }}-linux-amd64 dest=/usr/local/bin/serve remote_src=true mode=a+x
  when: newver.changed

- name: Generate SSH keys for deploy.copy-db plugin
  shell: test -f {{ secrets_dir }}/copy_db_ssh_key || ssh-keygen -b 2048 -t rsa -f {{ secrets_dir }}/copy_db_ssh_key -q -N ""
  args:
    creates: "{{ secrets_dir }}/copy_db_ssh_key"
  delegate_to: localhost
  run_once: true

- name: Copy serve local configs
  copy: src={{ item }} dest=/etc/serve/
  ignore_errors: true
  with_items:
    - "{{ playbook_dir }}/files/serve/conf.d"
    - "{{ playbook_dir }}/files/serve/include.d"
    - "{{ secrets_dir }}/copy_db_ssh_key"

- file: path="/etc/serve/copy_db_ssh_key" mode=400
