---
- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/consul-agent.yml
  when: inventory_hostname not in groups['tag_role_consul_server']
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/consul-agent.yml up -d --force-recreate
  when: compose.changed
