---
- ufw: logging=off

- name: allow SSH
  ufw: rule=allow port=22

- name: Allow all access from internal IPs
  ufw: rule=allow from="{{ item }}"
  with_items: "{{ ufw_allow_nets }}"

- name: Allow access to public ports
  ufw: rule=allow port="{{ item }}"
  with_items: "{{ ufw_public_ports }}"

- name: set firewall default policy
  ufw: state=enabled policy=reject
