---
- name: Copy docker-compose
  template: src=docker-compose.yml.j2 dest=/etc/compose/mesos-master.yml
  register: compose

- name: Run docker container
  command: docker-compose --file=/etc/compose/mesos-master.yml up -d --force-recreate
  when: compose.changed

- name: Save http routing
  uri:
    url: http://127.0.0.1:8500/v1/kv/services/routes/system/mesos-master
    method: PUT
    body_format: json
    body: '{ "routes": [ { "host": "mesos.{{ env_domain }}" } ] }'
  when: compose.changed
